from netbox_python.api.asn_range import asn_range
from netbox_python.api.circuits import circuits
from netbox_python.api.core import core
from netbox_python.api.dcim import dcim
from netbox_python.api.extras import extras
from netbox_python.api.ip_range import ip_range
from netbox_python.api.ipam import ipam
from netbox_python.api.plugins import plugins
from netbox_python.api.prefix import prefix
from netbox_python.api.tenancy import tenancy
from netbox_python.api.users import users
from netbox_python.api.virtualization import virtualization
from netbox_python.api.vlan_group import vlan_group
from netbox_python.api.wireless import wireless
